// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1) {
  return window['go']['main']['App']['Auth'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideConfig(arg1) {
  return window['go']['main']['App']['HideConfig'](arg1);
}

export function InstallBrowser() {
  return window['go']['main']['App']['InstallBrowser']();
}

export function IsAuthed() {
  return window['go']['main']['App']['IsAuthed']();
}

export function IsBrowserInstalled() {
  return window['go']['main']['App']['IsBrowserInstalled']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function NewConfig(arg1, arg2) {
  return window['go']['main']['App']['NewConfig'](arg1, arg2);
}

export function RunConfig(arg1) {
  return window['go']['main']['App']['RunConfig'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2);
}
